Repository takahiroanno2024/election2024, pull requests merged in 2024-07, with the labels that each got.

#255 Update democracy.md　荒らし対策
  docs/manifest/democracy.md
Labels: 民主主義

#154 東京都の少子化要因の多くが有配偶率低下であることの説明追加。
  docs/manifest/education.md
Labels: 教育・子育て

#42 Update economy.md
  docs/manifest/economy.md
Labels: 経済

#271 プッシュ型のメリット追加
  docs/manifest/administration.md
Labels: 行政

#268 東京都の役割
  docs/manifest/administration.md
Labels: 行政

#270 組織強化の明確化
  docs/manifest/administration.md
Labels: 行政

#256 Create Others & Energy
  README.md
  docs/index.md
  docs/manifest/others.md
  mkdocs.yml
Labels: その他

#286 障害福祉領域での専門職・連携強化・テクノロジー活用の強化
  docs/manifest/others.md
Labels: その他

#287 フリーランス・起業家の方に向けた、育休相当の支援
  docs/manifest/education.md
Labels: 教育・子育て

#288 不妊治療における書類提出作業オンライン化
  docs/manifest/education.md
Labels: 教育・子育て, 行政

#289 自動運転先進都市に、島しょ地域を追加。取り組み内容の具体化。
  docs/manifest/economy.md
Labels: 経済

#307 行政パートの構成見直し
  docs/manifest/administration.md
Labels: 行政
